Repository atalantus/Wokabel-App, pull requests merged in 2018-07, with the labels that each got.

#33 Updated Project and implemented WelcomeView
  .idea/codeStyles/Project.xml
  .idea/vcs.xml
  App/.gitignore
  App/.idea/assetWizardSettings.xml
  App/.idea/caches/build_file_checksums.ser
  App/app/build.gradle
  App/app/src/main/AndroidManifest.xml
  App/app/src/main/java/com/wokabel/app/wokabel/MainActivity.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/SubjectSelect.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/Welcome.java
  App/app/src/main/res/drawable/ic_dashboard_black_24dp.xml
  App/app/src/main/res/drawable/ic_person_black_24dp.xml
  App/app/src/main/res/drawable/ic_settings_black_24dp.xml
  App/app/src/main/res/layout/activity_main.xml
  App/app/src/main/res/layout/activity_subject_select.xml
  App/app/src/main/res/layout/activity_welcome.xml
  App/app/src/main/res/menu/navigation.xml
  App/app/src/main/res/values-de-rDE/strings.xml
  App/app/src/main/res/values/attrs.xml
  App/app/src/main/res/values/colors.xml
  App/app/src/main/res/values/dimens.xml
  App/app/src/main/res/values/strings.xml
  App/app/src/main/res/values/styles.xml
Labels: UI

#40 Implementierung der SharedPreferences
  App/.idea/assetWizardSettings.xml
  App/.idea/caches/build_file_checksums.ser
  App/app/src/main/AndroidManifest.xml
  App/app/src/main/java/com/wokabel/app/wokabel/WokabelApplication.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/preferences/Settings.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/preferences/SettingsDefaults.java
  App/app/src/main/java/com/wokabel/app/wokabel/viewModels/SubjectSelectViewModel.java
  App/app/src/main/java/com/wokabel/app/wokabel/viewModels/WelcomeViewModel.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/SubjectSelect.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/Welcome.java
  App/app/src/main/res/layout/activity_subject_select.xml
  App/app/src/main/res/values-de-rDE/strings.xml
  App/app/src/main/res/values/strings.xml
Labels: architektur, prio: normal

#43 Erste Implementierung der SubjectSelect Activity
  App/.gitignore
  App/.idea/caches/build_file_checksums.ser
  App/app/build.gradle
  App/app/src/main/AndroidManifest.xml
  App/app/src/main/java/com/wokabel/app/wokabel/views/Launch.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/ProfileFragment.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/RecyclerViewAdapter.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/SettingsFragment.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/SubjectSelect.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/SubjectsFragment.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/UnitDisplay.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/UnitSelect.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/Welcome.java
  App/app/src/main/res/drawable/ic_add_black_24dp.xml
  App/app/src/main/res/drawable/ic_edit_black_24dp.xml
  App/app/src/main/res/layout/activity_launch.xml
  App/app/src/main/res/layout/activity_subject_select.xml
  App/app/src/main/res/layout/activity_unit_display.xml
  App/app/src/main/res/layout/activity_unit_select.xml
  App/app/src/main/res/layout/fragment_profile.xml
  App/app/src/main/res/layout/fragment_settings.xml
  App/app/src/main/res/layout/fragment_subjects.xml
  App/app/src/main/res/layout/list_item_subject.xml
  App/app/src/main/res/values-de-rDE/strings.xml
  App/app/src/main/res/values/strings.xml
Labels: UI, prio: normal

#47 DatabaseAdapter
  App/.idea/caches/build_file_checksums.ser
  App/app/src/main/java/com/wokabel/app/wokabel/models/Subgroup.java
  App/app/src/main/java/com/wokabel/app/wokabel/models/Vocable.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/DatabaseAdapter.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/SubgroupDao.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/SupergroupDao.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/Typeconverter.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/VocableDao.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/SubjectSelect.java
Labels: datenspeicherung, prio: normal

#52 ViewModels & Launcher Logik
  App/.idea/caches/build_file_checksums.ser
  App/.idea/vcs.xml
  App/app/src/main/AndroidManifest.xml
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/DatabaseAdapter.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/SupergroupDao.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/WokabelDatabase.java
  App/app/src/main/java/com/wokabel/app/wokabel/viewModels/SubjectSelectViewModel.java
  App/app/src/main/java/com/wokabel/app/wokabel/viewModels/UnitSelectViewModel.java
  App/app/src/main/java/com/wokabel/app/wokabel/viewModels/WelcomeViewModel.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/Launch.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/ProfileFragment.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/RecyclerViewAdapter.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/SubjectSelect.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/SubjectsFragment.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/UnitSelect.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/Welcome.java
  App/app/src/main/res/layout/activity_unit_select.xml
  App/app/src/main/res/layout/fragment_profile.xml
  App/app/src/main/res/values/strings.xml
Labels: architektur, prio: normal

#59 SupergroupEntity Icons Spalte & Indizes
  App/.idea/caches/build_file_checksums.ser
  App/app/src/androidTest/java/com/wokabel/app/wokabel/ExampleInstrumentedTest.java
  App/app/src/androidTest/java/com/wokabel/app/wokabel/VocableInstrumentedTest.java
  App/app/src/main/java/com/wokabel/app/wokabel/models/Subgroup.java
  App/app/src/main/java/com/wokabel/app/wokabel/models/Supergroup.java
  App/app/src/main/java/com/wokabel/app/wokabel/models/Vocable.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/DatabaseAdapter.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/SupergroupDao.java
  App/app/src/test/java/com/wokabel/app/wokabel/ExampleUnitTest.java
Labels: datenspeicherung, prio: very high

#60 Abfrage-Algorithmus fertiggestellt
  App/.idea/caches/build_file_checksums.ser
  App/.idea/misc.xml
  App/app/build.gradle
  App/app/src/androidTest/java/com/wokabel/app/wokabel/VocabularyTestInstrumentedTest.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/vocabularyTest/VocabularyTest.java
  App/app/src/main/java/com/wokabel/app/wokabel/viewModels/VocabularyTestViewModel.java
Labels: abfrage, prio: normal

#66 Daten-Speicherung Abschluss (vorläufig)
  App/.idea/caches/build_file_checksums.ser
  App/app/src/androidTest/java/com/wokabel/app/wokabel/LiveDataTestUtil.java
  App/app/src/androidTest/java/com/wokabel/app/wokabel/room/SubgroupDaoInstrumentedTest.java
  App/app/src/androidTest/java/com/wokabel/app/wokabel/room/SupergroupDaoInstrumentedTest.java
  App/app/src/androidTest/java/com/wokabel/app/wokabel/room/TestData.java
  App/app/src/androidTest/java/com/wokabel/app/wokabel/room/VocableDaoInstrumentedTest.java
  App/app/src/main/assets/preset_eng-de.xml
  App/app/src/main/java/com/wokabel/app/wokabel/models/Vocable.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/XmlUtil/Xmlimport.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/DatabaseAdapter.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/SubgroupDao.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/SupergroupDao.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/VocableDao.java
  App/app/src/main/java/com/wokabel/app/wokabel/viewModels/UnitSelectViewModel.java
Labels: datenspeicherung, prio: very high

#67 Daten-Speicherung (quixfix)
  App/app/src/main/assets/preset_eng-de.xml
  App/app/src/main/java/com/wokabel/app/wokabel/services/XmlUtilities/XmlReader.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/DatabaseAdapter.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/SubgroupDao.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/SupergroupDao.java
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/VocableDao.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/Launch.java
Labels: datenspeicherung

#70 FINALE PULL REQUEST (ViewModels)
  App/app/src/main/AndroidManifest.xml
  App/app/src/main/java/com/wokabel/app/wokabel/services/room/DatabaseAdapter.java
  App/app/src/main/java/com/wokabel/app/wokabel/viewModels/EditSubjectViewModel.java
  App/app/src/main/java/com/wokabel/app/wokabel/viewModels/EditUnitViewModel.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/EditUnit.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/SubjectSelectAdapter.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/UnitSelect.java
  App/app/src/main/java/com/wokabel/app/wokabel/views/UnitSelectAdapter.java
  App/app/src/main/res/layout/activity_edit_unit.xml
  App/app/src/main/res/layout/list_item_unit.xml
  App/app/src/main/res/values/strings.xml
Labels: architektur, prio: normal
